### ISSUE TITLE
print "Hello" to standard error (System.out) 是不是写错了

### ISSUE THREAD

**Issue by kungua** [hcsp/create-a-psvm-method-and-print#67]
老师 在这道题目中有这样一行描述
![image](https://user-images.githubusercontent.com/52815012/63500012-9bb9ef00-c4fb-11e9-99cb-ffe6dbe4210a.png)
这行英文描述是不是与下面标准输出不符
改为
![image](https://user-images.githubusercontent.com/52815012/63500081-c310bc00-c4fb-11e9-8ea3-a5a213e23d66.png)
hui'bu会不会好一些~

**Comment by blindpirate** [comment]
谢谢！Fixed in https://github.com/hcsp/create-a-psvm-method-and-print/commit/0b03a2be4c3759ff06babec80544b6f41bb01e1d
